BlogDeployment:
  name: my-app-deployment
  replicas: 1
  app: my-backend-app
  image: 
    repository: 590183982624.dkr.ecr.us-east-1.amazonaws.com/alamzia23repo  #590183982624.dkr.ecr.us-east-1.amazonaws.com/alamzia23repo :v2.0.4
    tag: v2.0.7

servicefile:
  name: backend-service
  app: my-backend-app
  type: LoadBalancer #changed to NodePort from LoadBalancer

Secrets:
  name: my-app-secrets
  type: Opaque

readinessProbe:
  port: 5000

livenessProbe:
  port: 5000
  